//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mouse_Maze.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mouse_Maze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kmExXJuP/I93UJGs7J7gC/xNlqQe9MFw6B9B1Z0E4hkKxYo+hOdVfdcpVjRwwt/j6kYcqRVET8AiQX1jjBI6wtL0z7gQgEmfA/KvS7dx5YjQK9FvURT4PZphbuzzK9riM4eA+XNSk4oeGftqlM/NmlvTQhZg1khtkBLkO4E7GYBrSemIPNEZvHx2z8ttSgxFL3Yy5BNjRSlg/UZNNYaHDO84wCRz4QtGrs2HJwzp8teveLE7hpaWL8BGAw2esEHXUBLzPi4efRs/vmNErUprFb/8HVAchysZS+oDiW43IIprm+mnnnfQVgvGj1nHdb5z51YciMFayJDRCZXT6jmeJqjnjmf6ztaDYInUZpKT+t8+8LsiaIUjn0GPsiZjOyUenA4RA7L6xgH7lRhVNmcupA==.
        /// </summary>
        internal static string MMStats {
            get {
                return ResourceManager.GetString("MMStats", resourceCulture);
            }
        }
    }
}
